version: 2

updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "hashicorp/aws"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"

