version: 2.1
jobs:
  test:
    working_directory: ~/terraform-aws-rds-postgres
    docker:
      - image: ruby:2.6.0
    steps:
      - checkout
      - run: ./scripts/ci/common/install-git-crypt.sh
      - run: ./scripts/ci/steps/test.sh
  prerelease:
    working_directory: ~/terraform-aws-rds-postgres
    docker:
      - image: ruby:2.6.0
    steps:
      - checkout
      - run: ./scripts/ci/common/install-git-crypt.sh
      - run: ./scripts/ci/steps/prerelease.sh
  release:
    working_directory: ~/terraform-aws-rds-postgres
    docker:
      - image: ruby:2.6.0
    steps:
      - checkout
      - run: ./scripts/ci/common/install-git-crypt.sh
      - run: ./scripts/ci/steps/release.sh
workflows:
  version: 2
  pipeline:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
                - /^dependabot.*/
      - prerelease:
          requires:
            - test
          filters:
            branches:
              only: master
      - hold:
          type: approval
          requires:
            - prerelease
          filters:
            branches:
              only: master
      - release:
          requires:
            - hold
          filters:
            branches:
              only: master
