---
configuration_directory: "%{cwd}/examples/full"
state_file: "%{cwd}/state/full.tfstate"
vars:
  region: "%{hiera('region')}"
  availability_zones: "%{hiera('availability_zones')}"
  vpc_cidr: "%{hiera('vpc_cidr')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  private_zone_id: "%{hiera('private_zone_id')}"

  database_name: "%{hiera('database_name')}"
  database_master_user: "%{hiera('database_master_user')}"
  database_master_user_password: "%{hiera('database_master_user_password')}"
